# Copied and modified from the rimage crate github action.
# https://github.com/SalOne22/rimage/blob/main/.github/workflows/deploy.yml
name: deploy

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  deploy:
    name: deploy release
    runs-on: ubuntu-latest

    if: ${{ !github.event.repository.fork }}

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: get the weaving version
        id: weaving-meta
        run:
          echo "version=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[] | select(.name == "weaving").version')"
          >> "$GITHUB_OUTPUT"

      - name: retrieve ${{ matrix.target }} binary
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: weaving.yml
          commit: ${{ github.sha }}
          name: weaving binary (${{ matrix.target }})
          path: target

      - name: build archives
        working-directory: target
        run: |
          ARCHIVE_NAME="weaving-${{ steps.weaving-meta.outputs.version }}-${{ matrix.target }}"

          mkdir "$ARCHIVE_NAME"
          cp ../CHANGELOG.md ../README.md "$ARCHIVE_NAME"

          case '${{ matrix.target }}' in
            *-windows-*)
              cp ../LICENSE-APACHE "$ARCHIVE_NAME/LICENSE"
              cp weaving.exe "$ARCHIVE_NAME"
              zip "${ARCHIVE_NAME}.zip" "$ARCHIVE_NAME"/*;;
            *)
              cp ../LICENSE-APACHE ../LICENSE-MIT "$ARCHIVE_NAME"
              cp weaving "$ARCHIVE_NAME"
              tar -vczf "${ARCHIVE_NAME}.tar.gz" "$ARCHIVE_NAME"/*;;
          esac

      - name: create release notes
        run: tail -n +5 CHANGELOG.md | sed -e '/## \[v/,$d' > RELEASE_NOTES.txt

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.weaving-meta.outputs.version }}
          body_path: RELEASE_NOTES.txt
          prerelease: ${{ contains(steps.weaving-meta.outputs.version, 'next') }}
          files: |
            target/*.zip
            target/*.tar.gz
